apiVersion: v1
kind: Service
metadata:
  name: avillega-hello-world
spec:
	type: ClusterIP
  selector:
    owner: avillega
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: avillega-hello-world
spec:
  path: /
  to:
    kind: Service
    name: avillega-hello-world
  port:
    targetPort: 8090
